# FLUKE Coreference Resolution with GPT-5

This notebook evaluates coreference resolution robustness using OpenAI's GPT-5 model with FLUKE linguistic modifications.

In [1]:
# Standard imports
from datasets import load_dataset
import dspy
import openai
import os
import pandas as pd
import json
import glob
import time
import random
from dotenv import load_dotenv
from dspy.evaluate import Evaluate

# Import unified FLUKE utilities
from fluke_reasoning_utils import (
    REASONING_MODELS, REASONING_CONFIGS,
    remove_space, extract_classification_prediction,
    aggregate_results, highlight_drops_and_significance,
    compare_models
)

/Users/hungthinh/miniconda3/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Load environment variables
load_dotenv()
openai.api_key = os.getenv('OPENAI_API_KEY')
openai.organization = os.getenv('OPENAI_ORGANIZATION')

# Select GPT-5 configuration
CONFIG_NAME = 'standard'  # Options: 'standard', 'detailed', 'turbo'
config = REASONING_CONFIGS[CONFIG_NAME]

MODEL_NAME = config['model']
MODEL_ID = REASONING_MODELS[MODEL_NAME]

print(f"Configuration: {CONFIG_NAME}")
print(f"Model: {MODEL_NAME} ({MODEL_ID})")
print(f"Description: {config['description']}")

# Configure DSPy with GPT-5
# GPT-5 only supports temperature=1
lm = dspy.LM(MODEL_ID, max_tokens=250)
dspy.configure(lm=lm)

In [3]:
# Select GPT-5 configuration
CONFIG_NAME = 'standard'  # Options: 'standard', 'detailed', 'turbo'
config = REASONING_CONFIGS[CONFIG_NAME]

MODEL_NAME = config['model']
MODEL_ID = REASONING_MODELS[MODEL_NAME]

print(f"Configuration: {CONFIG_NAME}")
print(f"Model: {MODEL_NAME} ({MODEL_ID})")
print(f"Description: {config['description']}")

# Configure DSPy with GPT-5
lm = dspy.LM(MODEL_ID, temperature=1, max_tokens=20_000)
dspy.configure(lm=lm)

Configuration: standard
Model: gpt-5 (openai/gpt-5)
Description: Standard reasoning approach with GPT-5

## Load Coreference Data

In [4]:
# Load coreference dataset
ds = pd.read_json('../../../data/train_dev_test_data/coref/test.json')
ds = ds.to_dict('records')

print(f"Loaded {len(ds)} coreference samples")

# Split by label
positive_samples = []
negative_samples = []
for i, x in enumerate(ds):
    if x["label"] == 1:
        positive_samples.append((i, x))
    else:
        negative_samples.append((i, x))

print(f"Positive samples (coreferent): {len(positive_samples)}")
print(f"Negative samples (not coreferent): {len(negative_samples)}")

# Combine and shuffle
samples = positive_samples + negative_samples
random.shuffle(samples)

Loaded 1517 coreference samples
Positive samples (coreferent): 500
Negative samples (not coreferent): 1017

In [16]:
# Create examples
examples = [
    dspy.Example({
        "text": remove_space(r["text"]),
        "pronoun": r["pronoun"],
        "candidates": '0: ' + r["candidates"][0] + ', 1: ' + r["candidates"][1],
        "label": r['label']
    }).with_inputs("text", "pronoun", "candidates")
    for i, r in samples
]

# Test example
example = examples[0]
print(f"\nExample text: {example.text}")
print(f"Pronoun: {example.pronoun}")
print(f"Candidates: {example.candidates}")
print(f"Label: {example.label}")

Example text: Maira meanwhile is angry with Adhira so Bari Sarkar consoles her.
Pronoun: her
Candidates: 0: Maira, 1: Adhira
Label: 0

## Define Task with GPT-5

In [18]:
class GPT5Coref(dspy.Signature):
    """Determine the candidate that the given pronoun refers to in the text. Answer with the index of the candidate."""
    text = dspy.InputField()
    pronoun = dspy.InputField()
    candidates = dspy.InputField()
    label = dspy.OutputField(prefix='Answer:')

class GPT5CorefModule(dspy.Module):
    def __init__(self):
        super().__init__()
        self.prog = dspy.Predict(GPT5Coref)

    def forward(self, text, pronoun, candidates):
        return self.prog(text=text, pronoun=pronoun, candidates=candidates)

# Initialize module
gpt5_coref = GPT5CorefModule()

# Evaluation metric
def eval_metric(true, prediction, trace=None):
    pred = prediction.label
    parsed_answer = extract_classification_prediction(pred)
    return parsed_answer == str(true.label)

In [19]:
# Test single example
pred = gpt5_coref(text=example.text, pronoun=example.pronoun, candidates=example.candidates)
print(f"Text: {example.text}")
print(f"Pronoun: {example.pronoun}")
print(f"Candidates: {example.candidates}")
print(f"True Label: {example.label}")
print(f"Prediction: {pred.label}")
print(f"Correct: {eval_metric(example, pred)}")

Text: Maira meanwhile is angry with Adhira so Bari Sarkar consoles her.
Pronoun: her
Candidates: 0: Maira, 1: Adhira
True Label: 0
Prediction: 0
Correct: True

## Evaluate Original Dataset

In [25]:
# GPT-5 can handle larger batches
TEST_SIZE = 200  # Can increase for GPT-5
test_examples = examples

print(f"Evaluating {len(test_examples)} examples with GPT-5...")

evaluate = Evaluate(
    devset=test_examples,
    metric=eval_metric,
    num_threads=4,  # GPT-5 can handle more threads
    display_progress=True,
    display_table=10,
    return_all_scores=True
)

results = evaluate(gpt5_coref)

# Save results
print(results)
items = []
for sample in results['results']:
    print(sample)
    items.append({
        'text': sample[0]['text'],
        'pronoun': sample[0]['pronoun'],
        'candidates': str(sample[0]['candidates']),
        'label': sample[0]['label'],
        'pred': extract_classification_prediction(sample[1]['label']),
        'raw_output': sample[1]['label']
    })

df_result = pd.DataFrame(items)
output_file = f'../results/coref/{MODEL_NAME}-{CONFIG_NAME}-0shot-coref.csv'
df_result.to_csv(output_file, index=False)

print(f"\nGPT-5 Accuracy: {results['score']:.3f}")
print(f"Results saved to: {output_file}")

Evaluating 1517 examples with GPT-5...
Average Metric: 1258.00 / 1517 (82.9%): 100%|██████████| 1517/1517 [00:03<00:00, 482.77it/s]

2025/08/17 12:20:56 INFO dspy.evaluate.evaluate: Average Metric: 1258 / 1517 (82.9%)

,text,pronoun,candidates,example_label,pred_label,eval_metric
0,Maira meanwhile is angry with Adhira so Bari Sarkar consoles her.,her,"0: Maira, 1: Adhira",0,0,✔️ [True]
1,"Esaias was not related to Willem van de Velde, but he was the cous...",he,"0: Esaias, 1: Willem van de Velde",0,0,✔️ [True]
2,Ed Helms was cast as Derek Smeathe but scheduling conflicts preven...,him,"0: Derek Smeathe, 1: Ed Helms",1,1,✔️ [True]
3,"Indi asks Mink to stay, but she departs, leaving a note for Romeo.",she,"0: Indi, 1: Mink",0,1,
4,"Layla initially thinks Carolyn is stuck up, especially when she di...",she,"0: Layla, 1: Carolyn",1,1,✔️ [True]
5,"While searching, nurse Jill is killed upon encountering Michaela, ...",she,"0: nurse Jill, 1: Michaela",0,0,✔️ [True]
6,The spear easily pierced through the armor because it was too thin.,it,"0: The spear, 1: the armor",1,1,✔️ [True]
7,Anna Dalassene consented to this but forced Katherine to resign im...,she,"0: Katherine, 1: Anna Dalassene",0,0,✔️ [True]
8,Arushi does not listen to Sunaina when she tells him that she woul...,she,"0: Arushi, 1: Sunaina",1,1,✔️ [True]
9,"David truly loved and trusted Wolfgang now, where before he had be...",he,"0: David, 1: Wolfgang",0,0,✔️ [True]

EvaluationResult(score=82.93, results=<list of 1517 results>)
(Example({'text': 'Maira meanwhile is angry with Adhira so Bari Sarkar consoles her.', 'pronoun': 'her', 'candidates': '0: Maira, 1: Adhira', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Esaias was not related to Willem van de Velde, but he was the cousin of Jan van de Velde.', 'pronoun': 'he', 'candidates': '0: Esaias, 1: Willem van de Velde', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Ed Helms was cast as Derek Smeathe but scheduling conflicts prevented him from taking the role.', 'pronoun': 'him', 'candidates': '0: Derek Smeathe, 1: Ed Helms', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Indi asks Mink to stay, but she departs, leaving a note for Romeo.', 'pronoun': 'she', 'candidates': '0: Indi, 1: Mink', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': "Layla initially thinks Carolyn is stuck up, especially when she disagrees with his idea for Harold's buck's night.", 'pronoun': 'she', 'candidates': '0: Layla, 1: Carolyn', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'While searching, nurse Jill is killed upon encountering Michaela, and she is stabbed in the back with a scalpel.', 'pronoun': 'she', 'candidates': '0: nurse Jill, 1: Michaela', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'The spear easily pierced through the armor because it was too thin.', 'pronoun': 'it', 'candidates': '0: The spear, 1: the armor', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Anna Dalassene consented to this but forced Katherine to resign immediately afterwards; she was succeeded by Eustratios Garidas.', 'pronoun': 'she', 'candidates': '0: Katherine, 1: Anna Dalassene', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Arushi does not listen to Sunaina when she tells him that she would return her all the property.', 'pronoun': 'she', 'candidates': '0: Arushi, 1: Sunaina', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'David truly loved and trusted Wolfgang now, where before he had been hostile and spiteful toward him.', 'pronoun': 'he', 'candidates': '0: David, 1: Wolfgang', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Mark finally agrees to kill Serge, but he says that this will be the last order he will carry out.', 'pronoun': 'he', 'candidates': '0: Mark, 1: Serge', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': "Tom gave Ralph a lift to school so he wouldn't have to drive alone.", 'pronoun': 'he', 'candidates': '0: Tom, 1: Ralph', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Antietam was primarily a defensive battle against superior odds, although McClellan failed to exploit his advantage.', 'pronoun': 'his', 'candidates': '0: Antietam, 1: McClellan', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': 'Zu Ji was the eldest son of King Wu Ding but despite his kingly title he never succeeded his father as a Shang dynasty King of China.', 'pronoun': 'his', 'candidates': '0: King Wu Ding, 1: Zu Ji', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': 'Nina still loved Candice, but she knew they had no chance at happiness.', 'pronoun': 'she', 'candidates': '0: Nina, 1: Candice', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Zoey also feels more and more estranged from Erika, because of the lies she tells to hide her relationship with Loren.', 'pronoun': 'she', 'candidates': '0: Zoey, 1: Erika', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Peavy was hired by Taylor after he dismissed his previous butler, Edward F. Sands, for forging his signature on checks.', 'pronoun': 'he', 'candidates': '0: Peavy, 1: Taylor', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Alicia encourages Nathalie to fight back if anyone picks a fight with her.', 'pronoun': 'her', 'candidates': '0: Alicia, 1: Nathalie', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'The minister befriended King George so he could have some friends.', 'pronoun': 'he', 'candidates': '0: The minister, 1: King George', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), False)
(Example({'text': 'The heroes show up and try to kill the Aliens, but they can not and are laughed at.', 'pronoun': 'they', 'candidates': '0: The heroes, 1: the Aliens', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Jason built Rocky a robot, so he had more free time.', 'pronoun': 'he', 'candidates': '0: Jason, 1: Rocky', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Tania thinks about cancelling on Vanessa, but she later arrives with dessert.', 'pronoun': 'she', 'candidates': '0: Tania, 1: Vanessa', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Jacky is surprised that Rachel does not come, and is even more surprised when she realizes that Higgins is not there either.', 'pronoun': 'she', 'candidates': '0: Jacky, 1: Rachel', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Trick Or Treaters are celebrating the holiday earlier during the day at Church, but they cannot convince everybody to do it during the day.', 'pronoun': 'they', 'candidates': '0: Trick Or Treaters, 1: Church', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), False)
(Example({'text': 'The scientists gave the chimps some bananas because they were hungry.', 'pronoun': 'they', 'candidates': '0: the chimps, 1: some bananas', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Batman constantly tried to arrest the Joker, but he always manages to get out.', 'pronoun': 'he', 'candidates': '0: Batman, 1: the Joker', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': "Krishna agreed and let Rukmi go free, but not before having his head shaved as a visible sign of a warrior's defeat.", 'pronoun': 'his', 'candidates': '0: Krishna, 1: Rukmi', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': 'As Andrea in the crop duster passed over Susan, she could see the landing strip.', 'pronoun': 'she', 'candidates': '0: Andrea, 1: Susan', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'James invites Jordan to a three-on-three match but when he declines, he questions his loss of talent.', 'pronoun': 'he', 'candidates': '0: Jordan, 1: James', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Wade comes to see Daniel, but the most he gets out of him is a smile.', 'pronoun': 'he', 'candidates': '0: Wade, 1: Daniel', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Look! There is a shark swimming right below that duck! It had better get away to safety fast!', 'pronoun': 'It', 'candidates': '0: The shark, 1: The duck', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'The gym teachers trained the students because they wanted to teach them discipline.', 'pronoun': 'they', 'candidates': '0: The gym teachers, 1: the students', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Natalia goes to Joyces, but she is rebuffed by her former employer.', 'pronoun': 'her', 'candidates': '0: Natalia, 1: Joyces', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Ida becomes jealous and attempts to drown Tamarah, but Vincent arrives to save her.', 'pronoun': 'her', 'candidates': '0: Ida, 1: Tamarah', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': 'Rose then tried to kiss Katie, but she rejected her, so she made her feel uncomfortable by constantly flirting with her.', 'pronoun': 'she', 'candidates': '0: Rose, 1: Katie', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), False)
(Example({'text': 'Anne gave birth to a daughter last month. She is a very charming woman.', 'pronoun': 'She', 'candidates': "0: Anne, 1: Anne's daughter", 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Grace was happy to trade me her sweater for my jacket. She thinks it looks great on her.', 'pronoun': 'it', 'candidates': '0: The sweater, 1: The jacket', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'The hotel staff tended to the royal family, however, they felt the service was unsatisfactory.', 'pronoun': 'they', 'candidates': '0: The hotel staff, 1: the royal family', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Melanie turns Victoria down but then realizes that she is still in love with her.', 'pronoun': 'she', 'candidates': '0: Melanie, 1: Victoria', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'James occasionally visits Archie, but he starts to take a fancy to local school headteacher Katrina Finlay.', 'pronoun': 'he', 'candidates': '0: James, 1: Archie', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), False)
(Example({'text': "Sid explained his theory to Mark but he couldn't convince him.", 'pronoun': 'he', 'candidates': '0: Sid, 1: Mark', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'An infuriated McCauley tries to kill Waingro afterwards, but he escapes.', 'pronoun': 'he', 'candidates': '0: Waingro, 1: McCauley', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': "The man jumped on the neighbor's pool and he swam.", 'pronoun': 'he', 'candidates': '0: The man, 1: the neighbor', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Lee attended to Kearney, but he died of his wounds.', 'pronoun': 'he', 'candidates': '0: Kearney, 1: Lee', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), False)
(Example({'text': 'Mia can not bring herself to ask Jennifer out, so Tracy decides to help her.', 'pronoun': 'her', 'candidates': '0: Mia, 1: Jennifer', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'The patrons enjoyed the food made by the chefs immensely, so they paid very well to enjoy this meal.', 'pronoun': 'they', 'candidates': '0: The patrons, 1: the chefs', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Someone hit Billy in the face because he was being rude.', 'pronoun': 'he', 'candidates': '0: Someone, 1: Billy', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Daisy usually shows a strong affinity towards Laura, although she is often characterised as being more sophisticated than her.', 'pronoun': 'she', 'candidates': '0: Daisy, 1: Laura', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Jill saw Jane fall down, and she helped her up.', 'pronoun': 'she', 'candidates': '0: Jill, 1: Jane', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Donald Trump fired his servant, Luigi, but he can find another job elsewhere.', 'pronoun': 'he', 'candidates': '0: Donald Trump, 1: Luigi', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'The cheetah outran the antelope so it got to eat.', 'pronoun': 'it', 'candidates': '0: The cheetah, 1: the antelope', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Prost retired whereas Robert rejoined after being push-started and pitted to replace his front wing, trailing Nannini in the race.', 'pronoun': 'his', 'candidates': '0: Prost, 1: Robert', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': 'Samuel despises Carl, telling Bandini if he wants to win him over, he has to treat him poorly.', 'pronoun': 'he', 'candidates': '0: Samuel, 1: Carl', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': 'John asked Bill because he knew the answer.', 'pronoun': 'he', 'candidates': '0: John, 1: Bill', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Julian Holloway was originally cast to play Roger, but a BBC strike delayed filming by a week and he was replaced by Ken Campbell.', 'pronoun': 'he', 'candidates': '0: Roger, 1: Julian Holloway', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': 'Robic moved to Bruce when he was seven and lived at Radenac.', 'pronoun': 'he', 'candidates': '0: Robic, 1: Bruce', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Joe has more money than Adam since he has a better job.', 'pronoun': 'he', 'candidates': '0: Joe, 1: Adam', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': "Josse manage to find Gauthier, but he's in very bad shape.", 'pronoun': 'he', 'candidates': '0: Josse, 1: Gauthier', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Masuo tries repeatedly to court Jean, but every time he seems to make progress, something inevitably goes wrong.', 'pronoun': 'he', 'candidates': '0: Masuo, 1: Jean', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'We went to the lake, because a shark had been seen at the ocean beach, so it was a safer place to swim.', 'pronoun': 'it', 'candidates': '0: The lake, 1: The ocean beach', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': "Bradley married Dr. Vento, despite the fact that he didn't like doctors.", 'pronoun': 'he', 'candidates': '0: Bradley, 1: Dr. Vento', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), False)
(Example({'text': 'I poured water from the bottle into the cup until it was empty.', 'pronoun': 'it', 'candidates': '0: the bottle, 1: the cup', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Intel Performs better than AMD in the processing market, but they are more successful in the graphics market instead.', 'pronoun': 'they', 'candidates': '0: Intel, 1: AMD', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Jane Bingum presented strong evidence against Claire, so she would be able to win her case.', 'pronoun': 'she', 'candidates': '0: Jane Bingum, 1: Claire', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Reedburn was in love with Victor although his feelings were not reciprocated.', 'pronoun': 'his', 'candidates': '0: Reedburn, 1: Victor', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Mary had a little lamb until she was stolen by Cindy.', 'pronoun': 'she', 'candidates': '0: Mary, 1: a little lamb', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': "The Maker's madness takes control of several inmates, but is finally subdued by Thanos and several of his allies among the prisoners.", 'pronoun': 'his', 'candidates': '0: The Maker, 1: Thanos', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': 'Von Hoene could do an uncanny vocal impersonation of horror icon Boris Karloff, and so he was also the off-screen voice announcer for the show.', 'pronoun': 'he', 'candidates': '0: horror icon Boris Karloff, 1: Von Hoene', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': 'The Xhosa warriors were reluctant to attack the families and so they allowed them to pass and resupply the troops.', 'pronoun': 'them', 'candidates': '0: the families, 1: The Xhosa warriors', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Caroline was suspicious of what Madeline was doing, but no one believed her and she was fired from the clinic.', 'pronoun': 'her', 'candidates': '0: Caroline, 1: Madeline', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': "Penny offers Bennett drugs, but before she can accept, O'olish Amaneh appears and takes them home.", 'pronoun': 'she', 'candidates': '0: Penny, 1: Bennett', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)
(Example({'text': 'Jane was offered the role of Pam after she attended a screen test.', 'pronoun': 'she', 'candidates': '0: Jane, 1: Pam', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), False)
(Example({'text': 'Smith does away with Whitey but gives his old friend Sinclair a last chance.', 'pronoun': 'his', 'candidates': '0: Smith, 1: Whitey', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='0'
), True)
(Example({'text': 'Tyler finds Robbo Slade unconscious, after he was involved in a hit-and-run.', 'pronoun': 'he', 'candidates': '0: Tyler, 1: Robbo Slade', 'label': 1}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), True)
(Example({'text': 'Tina files a complaint against her boss Patricia Webster when she begins to sexually harass her.', 'pronoun': 'she', 'candidates': '0: Tina, 1: her boss Patricia Webster', 'label': 0}) (input_keys={'text', 'pronoun', 'candidates'}), Prediction(
    label='1'
), False)

## Evaluate Modifications

In [40]:
def evaluate_modified_set(data, program, max_samples=50):
    """Evaluate on modified dataset with GPT-5."""
    limited_data = data[:max_samples] if len(data) > max_samples else data
    
    mod_examples = [
        dspy.Example({
            "text": remove_space(r['modified_text']),
            "original_text": remove_space(r['original_text']),
            "pronoun": r['modified_pronoun'],
            "candidates": '0: ' + r["modified_candidates"][0] + ', 1: ' + r["modified_candidates"][1],
            "label": int(r.get('modified_label') if 'modified_label' in r else r['label']),
            "original_label": int(r['original_label'] if 'original_label' in r else r['label']),
            "type": r['type'] if 'type' in r else None,
            "id": r['index']
        }).with_inputs("text", "pronoun", "candidates")
        for r in limited_data
    ]
    
    evaluate = Evaluate(
        devset=mod_examples,
        metric=eval_metric,
        num_threads=4,  # GPT-5 can handle more threads
        display_progress=True,
        display_table=1,
        return_all_scores=True
    )
    
    return evaluate(program)

In [42]:
# Load original predictions
original_pred_file = f'../results/coref/{MODEL_NAME}-{CONFIG_NAME}-0shot-coref.csv'
if os.path.exists(original_pred_file):
    original_pred_ds = pd.read_csv(original_pred_file)
    original_pred_ds['text'] = original_pred_ds['text'].apply(remove_space)
    print(f"Loaded original GPT-5 predictions from {original_pred_file}")
else:
    print("Please run original evaluation first")
    original_pred_ds = None

# Test all modifications with GPT-5
json_files = glob.glob('../../../data/modified_data/coref/*_100.json')
# GPT-5 can handle more modifications

print(f"\nTesting {len(json_files)} modifications with GPT-5...")

for json_file in json_files:
    print(f"\nProcessing: {json_file.split('/')[-1]}")
    
    with open(json_file, 'r') as f:
        data = json.load(f)
    print(data[0])
    # GPT-5 can handle larger samples
    results_mod = evaluate_modified_set(data, gpt5_coref, max_samples=150)
    
    # Process results
    items = []
    for sample in results_mod['results']:
        item = {
            'text': sample[0]['text'],
            'original_text': sample[0]['original_text'],
            'pronoun': sample[0]['pronoun'],
            'candidates': str(sample[0]['candidates']),
            'type': sample[0]['type'],
            'modified_label': sample[0]['label'],
            'original_label': sample[0]['original_label'],
            'modified_pred': extract_classification_prediction(sample[1]['label']),
            'raw_output': sample[1]['label'],
            'id': sample[0]['id']
        }
        
        # Find original prediction
        if original_pred_ds is not None:
            matches = original_pred_ds[original_pred_ds.index == item['id']]
            item['original_pred'] = matches.iloc[0]['pred'] if not matches.empty else None
        else:
            item['original_pred'] = None
        
        items.append(item)
    
    df_mod = pd.DataFrame(items)
    mod_name = json_file.split('/')[-1].replace('.json', '')
    output_file = f'../results/coref/{MODEL_NAME}-{CONFIG_NAME}-0shot-{mod_name}.csv'
    df_mod.to_csv(output_file, index=False)
    
    print(f"Accuracy: {results_mod['score']:.3f}")
    print(f"Saved to: {output_file}")
    
    time.sleep(2)  # Shorter delay for GPT-5

Loaded original GPT-5 predictions from ../results/coref/gpt-5-standard-0shot-coref.csv

Testing 18 modifications with GPT-5...

Processing: casual_100.json
{'original_text': 'Sally becomes attracted to Bella, but she is disappointed to learn she is marrying Emily Vincent.', 'original_candidates': ['Sally', 'Bella'], 'original_pronoun': 'she', 'original_label': 1, 'modified_text': "Sally's got a crush on Bella, but she's bummed out to find out she's tying the knot with Emily Vincent.", 'type': 'casual', 'modified_candidates': ['Sally', 'Bella'], 'modified_pronoun': 'she', 'modified_label': 1, 'index': 1084}
Average Metric: 87.00 / 100 (87.0%): 100%|██████████| 100/100 [03:05<00:00,  1.86s/it]

2025/08/19 11:47:17 INFO dspy.evaluate.evaluate: Average Metric: 87 / 100 (87.0%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"Sally's got a crush on Bella, but she's bummed out to find out she...","Sally becomes attracted to Bella, but she is disappointed to learn...",she,"0: Sally, 1: Bella",1,1,casual,1084,0,

Accuracy: 87.000
Saved to: ../results/coref/gpt-5-standard-0shot-casual_100.csv

Processing: discourse_100.json
{'original_text': 'The villagers attempt to have the werewolves executed, but they are instead exiled by the clan leader.', 'original_candidates': ['the werewolves', 'The villagers'], 'original_pronoun': 'they', 'original_label': 0, 'modified_text': 'The villagers attempt to have the werewolves executed, however, they are instead exiled by the clan leader.', 'type': 'reverse', 'modified_candidates': ['the werewolves', 'The villagers'], 'modified_pronoun': 'they', 'modified_label': 0, 'index': 842}
Average Metric: 84.00 / 100 (84.0%): 100%|██████████| 100/100 [00:20<00:00,  4.91it/s]

2025/08/19 11:47:44 INFO dspy.evaluate.evaluate: Average Metric: 84 / 100 (84.0%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"The villagers attempt to have the werewolves executed, however, th...","The villagers attempt to have the werewolves executed, but they ar...",they,"0: the werewolves, 1: The villagers",0,0,reverse,842,0,✔️ [True]

Accuracy: 84.000
Saved to: ../results/coref/gpt-5-standard-0shot-discourse_100.csv

Processing: compound_word_100.json
{'original_text': 'Cathy realizes that Heather has overheard, so she is overcome by guilt and she runs out after her into a raging storm.', 'original_candidates': ['Cathy', 'Heather'], 'original_pronoun': 'her', 'original_label': 1, 'modified_text': 'Cathy realizes that Heather has overheard, so she is overcome by guilt and she runs out after her into a raging thunderstorm.', 'type': 'compound_word', 'modified_candidates': ['Cathy', 'Heather'], 'modified_pronoun': 'her', 'modified_label': 1, 'index': 55}
Average Metric: 88.00 / 96 (91.7%): 100%|██████████| 96/96 [00:09<00:00,  9.62it/s]

2025/08/19 11:48:01 INFO dspy.evaluate.evaluate: Average Metric: 88 / 96 (91.7%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"Cathy realizes that Heather has overheard, so she is overcome by g...","Cathy realizes that Heather has overheard, so she is overcome by g...",her,"0: Cathy, 1: Heather",1,1,compound_word,55,1,✔️ [True]

Accuracy: 91.670
Saved to: ../results/coref/gpt-5-standard-0shot-compound_word_100.csv

Processing: temporal_bias_100.json
{'original_text': 'Josie did not like Sarah, but she did not tell her.', 'original_candidates': ['Josie', 'Sarah'], 'original_pronoun': 'she', 'original_label': 0, 'modified_text': 'Josie did not fancy Sarah, but she did not tell her.', 'type': 'temporal_bias', 'modified_candidates': ['Josie', 'Sarah'], 'modified_pronoun': 'she', 'modified_label': 0, 'index': 315}
Average Metric: 90.00 / 100 (90.0%): 100%|██████████| 100/100 [00:03<00:00, 25.53it/s]

2025/08/19 11:48:09 INFO dspy.evaluate.evaluate: Average Metric: 90 / 100 (90.0%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"Josie did not fancy Sarah, but she did not tell her.","Josie did not like Sarah, but she did not tell her.",she,"0: Josie, 1: Sarah",0,0,temporal_bias,315,0,✔️ [True]

Accuracy: 90.000
Saved to: ../results/coref/gpt-5-standard-0shot-temporal_bias_100.csv

Processing: coordinating_conjunction_100.json
{'original_text': 'Shatterstar attempts to kill Arcade, but he only destroys a robotic double.', 'original_candidates': ['Arcade', 'Shatterstar'], 'original_pronoun': 'he', 'original_label': 1, 'modified_text': 'Shatterstar attempts to kill Arcade, but he only destroys and dismantles a robotic double.', 'type': 'coordinating_conjunction', 'modified_candidates': ['Arcade', 'Shatterstar'], 'modified_pronoun': 'he', 'modified_label': 1, 'index': 1482}
Average Metric: 83.00 / 97 (85.6%): 100%|██████████| 97/97 [00:04<00:00, 21.95it/s]

2025/08/19 11:48:17 INFO dspy.evaluate.evaluate: Average Metric: 83 / 97 (85.6%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"Shatterstar attempts to kill Arcade, but he only destroys and dism...","Shatterstar attempts to kill Arcade, but he only destroys a roboti...",he,"0: Arcade, 1: Shatterstar",1,1,coordinating_conjunction,1482,1,✔️ [True]

Accuracy: 85.570
Saved to: ../results/coref/gpt-5-standard-0shot-coordinating_conjunction_100.csv

Processing: capitalization_100.json
{'original_text': 'Lingad was defeated by Estelito Mendoza, but he raised charges of fraud which led to the staging of a new election for governor.', 'original_candidates': ['Lingad', 'Estelito Mendoza'], 'original_pronoun': 'he', 'original_label': 0, 'modified_text': 'Lingad was defeated by Estelito Mendoza, but he raised charges of FRAUD which led to the staging of a new election for governor.', 'modified_candidates': ['Lingad', 'Estelito Mendoza'], 'modified_pronoun': 'he', 'modified_label': 0, 'type': 'all_caps', 'index': 1219}
Average Metric: 94.00 / 99 (94.9%): 100%|██████████| 99/99 [00:02<00:00, 36.52it/s]

2025/08/19 11:48:22 INFO dspy.evaluate.evaluate: Average Metric: 94 / 99 (94.9%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"Lingad was defeated by Estelito Mendoza, but he raised charges of ...","Lingad was defeated by Estelito Mendoza, but he raised charges of ...",he,"0: Lingad, 1: Estelito Mendoza",0,0,all_caps,1219,0,✔️ [True]

Accuracy: 94.950
Saved to: ../results/coref/gpt-5-standard-0shot-capitalization_100.csv

Processing: dialectal_100.json
{'original_text': "Journalist Jack Anderson speculated that Watergate Special Prosecutor Archibald Cox had been fired because he had started to investigate Rebozo's role in Nixon accepting covert payments.", 'original_candidates': ['Journalist Jack Anderson', 'Watergate Special Prosecutor Archibald Cox'], 'original_pronoun': 'he', 'original_label': 1, 'modified_text': "Journalist Jack Anderson was thinking maybe Watergate Special Prosecutor Archibald Cox kena fired cos he starting to kaypoh into Rebozo's part in Nixon taking secret money like that.", 'type': 'singaporean_english', 'modified_candidates': ['Journalist Jack Anderson', 'Watergate Special Prosecutor Archibald Cox'], 'modified_pronoun': 'he', 'modified_label': 1, 'index': 1265}
Average Metric: 87.00 / 100 (87.0%): 100%|██████████| 100/100 [00:03<00:00, 31.81it/s]

2025/08/19 11:48:29 INFO dspy.evaluate.evaluate: Average Metric: 87 / 100 (87.0%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,Journalist Jack Anderson was thinking maybe Watergate Special Pros...,Journalist Jack Anderson speculated that Watergate Special Prosecu...,he,"0: Journalist Jack Anderson, 1: Watergate Special Prosecutor Archi...",1,1,singaporean_english,1265,1,✔️ [True]

Accuracy: 87.000
Saved to: ../results/coref/gpt-5-standard-0shot-dialectal_100.csv

Processing: sentiment_100.json
{'original_text': 'The cat was afraid of the dog because it was timid.', 'original_candidates': ['The cat', 'the dog'], 'original_pronoun': 'it', 'original_label': 0, 'modified_text': 'The cat was afraid of the friendly dog because it was timid.', 'type': 'sentiment', 'modified_candidates': ['The cat', 'the friendly dog'], 'modified_pronoun': 'it', 'modified_label': 0, 'index': 844}
Average Metric: 84.00 / 100 (84.0%): 100%|██████████| 100/100 [00:07<00:00, 14.19it/s]

2025/08/19 11:48:39 INFO dspy.evaluate.evaluate: Average Metric: 84 / 100 (84.0%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,The cat was afraid of the friendly dog because it was timid.,The cat was afraid of the dog because it was timid.,it,"0: The cat, 1: the friendly dog",0,0,sentiment,844,0,✔️ [True]

Accuracy: 84.000
Saved to: ../results/coref/gpt-5-standard-0shot-sentiment_100.csv

Processing: grammatical_role_100.json
{'original_text': 'Lakshman asked Vivan to get him some ice cream because he was hot.', 'original_candidates': ['Lakshman', 'Vivan'], 'original_pronoun': 'he', 'original_label': 0, 'modified_text': 'Vivan asked Lakshman to get him some ice cream because he was hot.', 'type': 'grammatical_role', 'modified_candidates': ['Vivan', 'Lakshman'], 'modified_pronoun': 'he', 'modified_label': 0, 'test': 'grammatical_role', 'index': 1455}
Average Metric: 60.00 / 72 (83.3%): 100%|██████████| 72/72 [00:01<00:00, 61.60it/s]

2025/08/19 11:48:44 INFO dspy.evaluate.evaluate: Average Metric: 60 / 72 (83.3%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,Vivan asked Lakshman to get him some ice cream because he was hot.,Lakshman asked Vivan to get him some ice cream because he was hot.,he,"0: Vivan, 1: Lakshman",0,0,grammatical_role,1455,0,✔️ [True]

Accuracy: 83.330
Saved to: ../results/coref/gpt-5-standard-0shot-grammatical_role_100.csv

Processing: length_bias_100.json
{'original_text': "Janis is ordered to kill Noelia, but doesn't know if she can go along with this.", 'original_candidates': ['Janis', 'Noelia'], 'original_pronoun': 'she', 'original_label': 0, 'modified_text': 'Janis has been ordered to kill Noelia, but she is unsure if she can actually go along with this plan.', 'type': 'length_bias', 'modified_candidates': ['Janis', 'Noelia'], 'modified_pronoun': 'she', 'modified_label': 0, 'index': 131}
Average Metric: 90.00 / 99 (90.9%): 100%|██████████| 99/99 [00:00<00:00, 156.47it/s]

2025/08/19 11:48:49 INFO dspy.evaluate.evaluate: Average Metric: 90 / 99 (90.9%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"Janis has been ordered to kill Noelia, but she is unsure if she ca...","Janis is ordered to kill Noelia, but doesn't know if she can go al...",she,"0: Janis, 1: Noelia",0,0,length_bias,131,0,✔️ [True]

Accuracy: 90.910
Saved to: ../results/coref/gpt-5-standard-0shot-length_bias_100.csv

Processing: concept_replacement_100.json
{'original_text': 'Dan walks away from Samuel and he tries running after him, but he trips and falls.', 'original_candidates': ['Dan', 'Samuel'], 'original_pronoun': 'him', 'original_label': 0, 'modified_text': 'Dan walks away from Samuel and he tries plarding after him, but he trips and falls.', 'type': 'nonce', 'modified_candidates': ['Dan', 'Samuel'], 'modified_pronoun': 'him', 'modified_label': 0, 'index': 285}
Average Metric: 78.00 / 100 (78.0%): 100%|██████████| 100/100 [00:01<00:00, 69.31it/s]

2025/08/19 11:48:52 INFO dspy.evaluate.evaluate: Average Metric: 78 / 100 (78.0%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"Dan walks away from Samuel and he tries plarding after him, but he...","Dan walks away from Samuel and he tries running after him, but he ...",him,"0: Dan, 1: Samuel",0,0,nonce,285,0,✔️ [True]

Accuracy: 78.000
Saved to: ../results/coref/gpt-5-standard-0shot-concept_replacement_100.csv

Processing: typo_bias_100.json
{'original_text': 'Jason built Rocky a robot, and he gave it to him.', 'original_pronoun': 'he', 'original_candidates': ['Jason', 'Rocky'], 'modified_text': 'Jason built Rocky a robot, and he gave it to himm.', 'type': 'addition', 'original_label': 0, 'modified_label': 0, 'modified_pronoun': 'he', 'modified_candidates': ['Jason', 'Rocky'], 'index': 1007}
Average Metric: 83.00 / 98 (84.7%): 100%|██████████| 98/98 [00:03<00:00, 29.52it/s]

2025/08/19 11:48:59 INFO dspy.evaluate.evaluate: Average Metric: 83 / 98 (84.7%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"Jason built Rocky a robot, and he gave it to himm.","Jason built Rocky a robot, and he gave it to him.",he,"0: Jason, 1: Rocky",0,0,addition,1007,0,✔️ [True]

Accuracy: 84.690
Saved to: ../results/coref/gpt-5-standard-0shot-typo_bias_100.csv

Processing: geographical_bias_100.json
{'original_text': 'Trotsky refused to support Lenin since he was waiting to see whether German workers would rebel and whether German soldiers would refuse to follow orders.', 'original_candidates': ['Trotsky', 'Lenin'], 'original_pronoun': 'he', 'original_label': 1, 'modified_text': 'Yosuo refused to support Emilio since he was waiting to see whether Chuukese workers would rebel and whether Chuukese soldiers would refuse to follow orders.', 'type': 'geographical_bias', 'modified_candidates': ['Yosuo', 'Emilio'], 'modified_pronoun': 'he', 'modified_label': 1, 'index': 894}
Average Metric: 83.00 / 100 (83.0%): 100%|██████████| 100/100 [00:04<00:00, 20.32it/s]

2025/08/19 11:49:06 INFO dspy.evaluate.evaluate: Average Metric: 83 / 100 (83.0%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,Yosuo refused to support Emilio since he was waiting to see whethe...,Trotsky refused to support Lenin since he was waiting to see wheth...,he,"0: Yosuo, 1: Emilio",1,1,geographical_bias,894,0,

Accuracy: 83.000
Saved to: ../results/coref/gpt-5-standard-0shot-geographical_bias_100.csv

Processing: punctuation_100.json
{'original_text': 'The cat was afraid of the dog because it was timid.', 'original_pronoun': 'it', 'original_candidates': ['The cat', 'the dog'], 'modified_text': 'The cat was afraid of the dog, because it was timid.', 'type': 'addition', 'original_label': 0, 'modified_label': 0, 'modified_pronoun': 'it', 'modified_candidates': ['The cat', 'the dog'], 'index': 844}
Average Metric: 91.00 / 99 (91.9%): 100%|██████████| 99/99 [00:01<00:00, 72.20it/s]

2025/08/19 11:49:10 INFO dspy.evaluate.evaluate: Average Metric: 91 / 99 (91.9%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"The cat was afraid of the dog, because it was timid.",The cat was afraid of the dog because it was timid.,it,"0: The cat, 1: the dog",0,0,addition,844,0,✔️ [True]

Accuracy: 91.920
Saved to: ../results/coref/gpt-5-standard-0shot-punctuation_100.csv

Processing: derivation_100.json
{'original_text': 'The blimp hit the tree because it was in the way.', 'original_candidates': ['The blimp', 'the tree'], 'original_pronoun': 'it', 'original_label': 1, 'modified_text': 'The blimp impacted the tree because it was obstructing.', 'type': 'derivation', 'modified_candidates': ['The blimp', 'the tree'], 'modified_pronoun': 'it', 'modified_label': 1, 'index': 1203}
Average Metric: 89.00 / 98 (90.8%): 100%|██████████| 98/98 [00:01<00:00, 59.59it/s]

2025/08/19 11:49:14 INFO dspy.evaluate.evaluate: Average Metric: 89 / 98 (90.8%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,The blimp impacted the tree because it was obstructing.,The blimp hit the tree because it was in the way.,it,"0: The blimp, 1: the tree",1,1,derivation,1203,1,✔️ [True]

Accuracy: 90.820
Saved to: ../results/coref/gpt-5-standard-0shot-derivation_100.csv

Processing: active_to_passive_100.json
{'original_text': 'The campers turned on their flashlights because it was dark without them.', 'original_candidates': ['The campers', 'their flashlights'], 'original_pronoun': 'them', 'original_label': 1, 'modified_text': 'The flashlights were turned on by the campers because it was dark without them.', 'type': 'active_to_passive', 'modified_candidates': ['the campers', 'The flashlights'], 'modified_pronoun': 'them', 'modified_label': 1, 'index': 512}
Average Metric: 84.00 / 95 (88.4%): 100%|██████████| 95/95 [00:01<00:00, 62.57it/s]

2025/08/19 11:49:18 INFO dspy.evaluate.evaluate: Average Metric: 84 / 95 (88.4%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,The flashlights were turned on by the campers because it was dark ...,The campers turned on their flashlights because it was dark withou...,them,"0: the campers, 1: The flashlights",1,1,active_to_passive,512,1,✔️ [True]

Accuracy: 88.420
Saved to: ../results/coref/gpt-5-standard-0shot-active_to_passive_100.csv

Processing: singlish_100.json
{'original_text': 'The delivery truck zoomed by the school bus because it was going so fast.', 'original_pronoun': 'it', 'original_candidates': '0: the delivery truck, 1: the school bus', 'label': 0, 'index': 1284, 'modified_pronoun': 'it', 'modified_candidates': '0: delivery lorry, 1: the school bus', 'type': 'singaporean_english', 'modified_text': 'The delivery lorry zoom past the school bus lor, cos it was going so fast.', 'modified_label': 0, 'original_label': 0}
Average Metric: 76.00 / 102 (74.5%): 100%|██████████| 102/102 [00:01<00:00, 95.06it/s]

2025/08/19 11:49:21 INFO dspy.evaluate.evaluate: Average Metric: 76 / 102 (74.5%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,"The delivery lorry zoom past the school bus lor, cos it was going ...",The delivery truck zoomed by the school bus because it was going s...,it,"0: 0, 1: :",0,0,singaporean_english,1284,0,✔️ [True]

Accuracy: 74.510
Saved to: ../results/coref/gpt-5-standard-0shot-singlish_100.csv

Processing: negation_100.json
{'original_text': 'Kathy paid Jane to leave but she returned several weeks later.', 'original_candidates': ['Kathy', 'Jane'], 'original_pronoun': 'she', 'original_label': 1, 'modified_text': 'Kathy paid Jane to leave but she did not return several weeks later.', 'type': 'verbal', 'modified_candidates': ['Kathy', 'Jane'], 'modified_pronoun': 'she', 'modified_label': 1, 'test': 'negation', 'index': 991}
Average Metric: 72.00 / 98 (73.5%): 100%|██████████| 98/98 [00:01<00:00, 62.24it/s]

2025/08/19 11:49:25 INFO dspy.evaluate.evaluate: Average Metric: 72 / 98 (73.5%)

,text,original_text,pronoun,candidates,example_label,original_label,type,id,pred_label,eval_metric
0,Kathy paid Jane to leave but she did not return several weeks later.,Kathy paid Jane to leave but she returned several weeks later.,she,"0: Kathy, 1: Jane",1,1,verbal,991,1,✔️ [True]

Accuracy: 73.470
Saved to: ../results/coref/gpt-5-standard-0shot-negation_100.csv

## Chain-of-Thought with GPT-5

In [ ]:
class CoTGPT5Coref(dspy.Module):
    def __init__(self):
        super().__init__()
        self.prog = dspy.ChainOfThought(GPT5Coref)

    def forward(self, text, pronoun, candidates):
        return self.prog(text=text, pronoun=pronoun, candidates=candidates)

# Test CoT
cot_gpt5_coref = CoTGPT5Coref()
pred_cot = cot_gpt5_coref(text=example.text, pronoun=example.pronoun, candidates=example.candidates)
print("Chain-of-Thought with GPT-5:")
print(f"Text: {example.text}")
print(f"Pronoun: {example.pronoun}")
print(f"Candidates: {example.candidates}")
print(f"\nReasoning: {pred_cot.reasoning if hasattr(pred_cot, 'reasoning') else 'N/A'}")
print(f"\nPrediction: {pred_cot.label}")

## Aggregate Results

In [ ]:
# Aggregate all modification results
result_files = glob.glob(f'results/coref/{MODEL_NAME}-{CONFIG_NAME}-0shot-*_100.csv')

if result_files:
    results_df = aggregate_results(
        result_files,
        task_name='coreference_resolution',
        model_name=f'{MODEL_NAME}-{CONFIG_NAME}'
    )
    
    if not results_df.empty:
        # Display summary
        print(f"\n{MODEL_NAME}-{CONFIG_NAME} Results Summary:")
        print(results_df[['modification', 'original_res', 'modified_res', 'difference', 'samples']])
        
        # Save aggregated results
        output_file = f'results/coref/{MODEL_NAME}-{CONFIG_NAME}-DP.csv'
        results_df.to_csv(output_file, index=False)
        print(f"\nAggregated results saved to: {output_file}")
        
        # Display styled results
        styled_df = results_df.round(3).style.apply(highlight_drops_and_significance, axis=1)
        display(styled_df)
else:
    print("No result files found to aggregate")

## Model Comparison

In [ ]:
# Compare GPT-5 with other models
comparison_files = {
    'GPT-5': f'results/coref/{MODEL_NAME}-{CONFIG_NAME}-0shot-coref.csv',
    'GPT-4o': 'results/coref/gpt4o-0shot-coref.csv',
    'Claude-3.5': 'results/coref/claude-3-5-sonnet-0shot-coref.csv',
    'o3-2025-04-16': 'results/coref/o3-2025-04-16-standard-0shot-coref.csv',
    'Mixtral-8x22B': 'results/coref/mixtral-8x22b-0shot-coref.csv'
}

comparison_df = compare_models(comparison_files, task_name='coreference_resolution')

if not comparison_df.empty:
    print("\nModel Comparison (including GPT-5):")
    print(comparison_df)
    
    # Calculate GPT-5 improvement
    if 'GPT-5' in comparison_df['Model'].values:
        gpt5_acc = comparison_df[comparison_df['Model'] == 'GPT-5']['Accuracy'].values[0]
        other_accs = comparison_df[comparison_df['Model'] != 'GPT-5']['Accuracy'].values
        if len(other_accs) > 0:
            avg_others = other_accs.mean()
            improvement = gpt5_acc - avg_others
            print(f"\nGPT-5 Performance: {gpt5_acc:.3f}")
            print(f"Average of other models: {avg_others:.3f}")
            print(f"GPT-5 improvement: {improvement:+.3f} ({improvement*100:+.1f}%)")
    
    # Highlight best performer
    def highlight_max(s):
        is_max = s == s.max()
        return ['background-color: green; color: white' if v else '' for v in is_max]
    
    styled_comparison = comparison_df.style.apply(highlight_max, subset=['Accuracy'])
    display(styled_comparison)
else:
    print("No comparison data available")

## GPT-5 Performance Analysis

In [ ]:
print(f"\n{'='*60}")
print(f"FLUKE Coreference Resolution with GPT-5 Complete!")
print(f"{'='*60}")

if 'results' in locals():
    print(f"\nBase accuracy: {results[0]:.3f}")

if 'results_df' in locals() and not results_df.empty:
    avg_row = results_df[results_df['modification'] == 'average'].iloc[0]
    print(f"Average robustness drop: {avg_row['difference']:.3f}")
    print(f"Modifications tested: {len(results_df) - 1}")

print(f"\nGPT-5 Configuration: {config['description']}")
print(f"\nKey advantages of GPT-5:")
print("• Advanced pronoun resolution capabilities")
print("• Better understanding of grammatical agreement")
print("• Improved semantic plausibility reasoning")
print("• Faster inference than o3 models")
print("• Higher throughput with multi-threading")

print(f"\nFiles saved in: results/coref/")